# Generated by Django 3.2.7 on 2021-10-28 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('name', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SMA', 'SMA'), ('EMA', 'EMA')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_value', models.CharField(max_length=48)),
                ('is_signalable', models.BooleanField(default=False)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='cryptocurrency.coin')),
                ('current_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_currency', to='cryptocurrency.coin')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocurrency.technical_analysis')),
            ],
        ),
    ]
